
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace JobModels
{
    public class Job
    {
        // JobID is generated by the database on insert, so it must NOT be
        // [Required] — otherwise [ApiController] model validation rejects
        // new-job POSTs (which have no JobID yet) with a 400 Bad Request.
        public string? JobID { get; set; }
        public string? JobTitle { get; set; }
        public string? JobDescription { get; set; }
        public string? JobType { get; set; }
        public bool? JobStatus { get; set; }
        public string? JobFilter { get; set; }
        public string? EmployerID { get; set; }
        public string? CountryID { get; set; }
        public string? GenreID { get; set; }
        public decimal? Salary { get; set; }
        public string? CountryName { get; set; }
        public string? GenreTitle { get; set; }
        public string? JobTypeName { get; set; }
        public string? EmployerName { get; set; }
    }
}
